apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: default
spec:
  selector:
    component: elasticsearch
    role: default
  ports:
  - name: http
    port: 9200
#type: LoadBalancer
